### ISSUE TITLE
后续更新配置问题

### ISSUE THREAD

**Issue by kingkongchow** [loyejaotdiqr47123/rdpwrap#1]
代码小白，请问后续从sebaxakerhtc那拿到了对应的 termsrv.dll后 需要怎么才能写入到老哥这个程序里去，谢谢了。！

**Comment by loyejaotdiqr47123** [comment]
？啥意思？

**Comment by loyejaotdiqr47123** [comment]
我这里的ini直接使用的是seb的源

**Comment by loyejaotdiqr47123** [comment]
你可以直接使用我修改的rdpwrap

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.1.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/14545821/RDPWrap-v1.8.1.zip)
可以直接使用这个进行破解

**Comment by loyejaotdiqr47123** [comment]
> 代码小白，请问后续从sebaxakerhtc那拿到了对应的 termsrv.dll后 需要怎么才能写入到老哥这个程序里去，谢谢了。！

你可以直接使用https://github.com/loyejaotdiqr47123/rdpwrap/releases/tag/v1.8.1
这个修改版rdpwrap进行破解

**Comment by loyejaotdiqr47123** [comment]
已经是seb的源了，并且他ini是联网下载的

**Comment by loyejaotdiqr47123** [comment]
@kingkongchow https://blog.csdn.net/m0_46343087/article/details/136512940?spm=1001.2014.3001.5502
这篇文章是你写的吗？

**Comment by loyejaotdiqr47123** [comment]
@kingkongchow 跟进，sebaxakerhtc不在更新项目，ini将在本项目更新
