### ISSUE TITLE
Windows 11 termsrv.dll version 10.0.22621.3447 Not Supported

### ISSUE THREAD

**Issue by Dark1886** [loyejaotdiqr47123/rdpwrap#12]

**Comment by loyejaotdiqr47123** [comment]
[https://github.com/loyejaotdiqr47123/rdpwrap/commit/9b2df503c4a7217aa13c200de9fd4420ea320b0b](https://github.com/loyejaotdiqr47123/rdpwrap/commit/9b2df503c4a7217aa13c200de9fd4420ea320b0b)
