### ISSUE TITLE
W11 10.0.22000.2899 instant service crash

### ISSUE THREAD

**Issue by phoenX80** [loyejaotdiqr47123/rdpwrap#13]
I get this instant crash of the RDP Service when I install RDP Wrapper:

Name der fehlerhaften Anwendung: svchost.exe_TermService, Version: 10.0.22000.2600, Zeitstempel: 0x86a2ea8d
Name des fehlerhaften Moduls: rdpwrap.dll, Version: 0.0.0.0, Zeitstempel: 0x65d1bab3
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000007d121
ID des fehlerhaften Prozesses: 0x2f4
Startzeit der fehlerhaften Anwendung: 0x01da8cab9369e347
Pfad der fehlerhaften Anwendung: C:\WINDOWS\System32\svchost.exe
Pfad des fehlerhaften Moduls: c:\program files\rdp wrapper\rdpwrap.dll
Berichtskennung: 7d4376f6-0100-461b-91a6-2de9119d3c91
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
[termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/14955463/termsrv.zip)

The fact this refers to 2600 when the original is 2899 is correct I suppose? Anything I can try?

**Comment by phoenX80** [comment]
![Screenshot (103)](https://github.com/loyejaotdiqr47123/rdpwrap/assets/28687055/31e37cd7-f313-4106-a1df-d78f8bc57855)

**Comment by loyejaotdiqr47123** [comment]
> I get this instant crash of the RDP Service when I install RDP Wrapper:
> 
> Name der fehlerhaften Anwendung: svchost.exe_TermService, Version: 10.0.22000.2600, Zeitstempel: 0x86a2ea8d Name des fehlerhaften Moduls: rdpwrap.dll, Version: 0.0.0.0, Zeitstempel: 0x65d1bab3 Ausnahmecode: 0xc0000005 Fehleroffset: 0x000000000007d121 ID des fehlerhaften Prozesses: 0x2f4 Startzeit der fehlerhaften Anwendung: 0x01da8cab9369e347 Pfad der fehlerhaften Anwendung: C:\WINDOWS\System32\svchost.exe Pfad des fehlerhaften Moduls: c:\program files\rdp wrapper\rdpwrap.dll Berichtskennung: 7d4376f6-0100-461b-91a6-2de9119d3c91 Vollständiger Name des fehlerhaften Pakets: Anwendungs-ID, die relativ zum fehlerhaften Paket ist: [termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/14955463/termsrv.zip)
> 
> The fact this refers to 2600 when the original is 2899 is correct I suppose? Anything I can try?

[Uploading SuperRDP2_ini-2024-4-11.zip…]()
Try this.

**Comment by phoenX80** [comment]
> Try this.

Unfortunatley the exact same issue. I had RDP wrapper running till 2 days ago, seems the last update really messed it up and I cant uninstall the f.ing update.

[https://github.com/anhkgg/SuperRDP/issues/299](url)

**Comment by loyejaotdiqr47123** [comment]
> I get this instant crash of the RDP Service when I install RDP Wrapper:
> 
> Name der fehlerhaften Anwendung: svchost.exe_TermService, Version: 10.0.22000.2600, Zeitstempel: 0x86a2ea8d Name des fehlerhaften Moduls: rdpwrap.dll, Version: 0.0.0.0, Zeitstempel: 0x65d1bab3 Ausnahmecode: 0xc0000005 Fehleroffset: 0x000000000007d121 ID des fehlerhaften Prozesses: 0x2f4 Startzeit der fehlerhaften Anwendung: 0x01da8cab9369e347 Pfad der fehlerhaften Anwendung: C:\WINDOWS\System32\svchost.exe Pfad des fehlerhaften Moduls: c:\program files\rdp wrapper\rdpwrap.dll Berichtskennung: 7d4376f6-0100-461b-91a6-2de9119d3c91 Vollständiger Name des fehlerhaften Pakets: Anwendungs-ID, die relativ zum fehlerhaften Paket ist: [termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/14955463/termsrv.zip)
> 
> The fact this refers to 2600 when the original is 2899 is correct I suppose? Anything I can try?
Please check if c:\program files\rdp wrapper\rdpwrap.dll exists!

**Comment by phoenX80** [comment]
Did you accidently delete your text?
It says something about ID1056 while installing, this seems certificate related???

https://www.gradenegger.eu/en/details-of-the-event-with-id-1056-of-the-source-microsoft-windows-terminal-services-remote-connection-manager/

...
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[*] Configuring registry...
[*] Configuring firewall...
...

**Comment by loyejaotdiqr47123** [comment]
> Did you accidently delete your text? It says something about ID1056 while installing, this seems certificate related???
> 
> https://www.gradenegger.eu/en/details-of-the-event-with-id-1056-of-the-source-microsoft-windows-terminal-services-remote-connection-manager/
> 
> ... [_] Terminating service... [_] Starting TermService... [-] StartService error (code 1056). [_] Configuring registry... [_] Configuring firewall... ...

No.rdpwrap does not operate the certificate

**Comment by phoenX80** [comment]
No it is crashing, that's what my post was about. It probably patches successfully but MS seems to catch the alteration stops the service. There is someone else on git with the same issue.

**Comment by loyejaotdiqr47123** [comment]
Do you have a file (rdpwrap.log) in c:/

**Comment by phoenX80** [comment]
no

**Comment by loyejaotdiqr47123** [comment]
@phoenX80 [RDPWrap-1.8.3.zip](https://github.com/DuoStream/Duo/files/14970582/RDPWrap-1.8.3.zip)
