### ISSUE TITLE
Windows 11 Pro 10.0.22621.3447 Stopped, Not listening

### ISSUE THREAD

**Issue by manuel231509** [loyejaotdiqr47123/rdpwrap#15]
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/75493236/c4816a32-069a-49f9-a102-8979e3e149bf)
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/75493236/e2ea26b8-7bd2-4ef2-9e85-fde09dae2ee5)

**Comment by loyejaotdiqr47123** [comment]
Duplicate of #14
