### ISSUE TITLE
更新写入ini失败

### ISSUE THREAD

**Issue by Mapaler** [loyejaotdiqr47123/rdpwrap#18]
![WindowsTerminal_管理员_命令提示符_-_update bat_0265](https://github.com/loyejaotdiqr47123/rdpwrap/assets/6565860/24cf6d34-cf13-42eb-a36b-7c227387e886)

家里和单位都有这个问题，尝试把`C:\Program Files\RDP Wrapper\`权限设为所有人都可以修改，也还是`[-] Failed to write INI file.`

![dllhost_RDP_Wrapper的高级安全设置_0266](https://github.com/loyejaotdiqr47123/rdpwrap/assets/6565860/ae04f994-7899-4352-93ba-7426444e0589)

**Comment by loyejaotdiqr47123** [comment]
重新安装建议

**Comment by loyejaotdiqr47123** [comment]
对的，这个的话应该是系统本身的问题，解决不了



***@***.***
 
发件人： 枫谷剑仙
发送时间： 2024-04-22 17:51
收件人： loyejaotdiqr47123/rdpwrap
抄送： bobo; Assign
主题： Re: [loyejaotdiqr47123/rdpwrap] 更新写入ini失败 (Issue #18)
每次都卸载重新安装？

**Comment by loyejaotdiqr47123** [comment]
@Mapaler   你试下[https://github.com/sebaxakerhtc/rdpwrap/releases](https://github.com/sebaxakerhtc/rdpwrap/releases)
这个问题的话，等我期中考完再说

**Comment by Mapaler** [comment]
我之前就用的这个，这个不更新了我才用的你的

**Comment by loyejaotdiqr47123** [comment]
我现在拿到seb仓库的权限了，直接用他的就行

**Comment by loyejaotdiqr47123** [comment]
这个是系统自身策略问题，可以先net stop  termservice /y 停止服务后执行update.bat

**Comment by Mapaler** [comment]
> 不能用就直接去他仓库提issues，这个仓库我开自动同步进行

因为之前是 Archive 了，根本不能提 Issues

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/102934154/0f630ecc-708c-4d79-a269-886d386767f5)

n天前就取消存档了

**Comment by loyejaotdiqr47123** [comment]
Reopen

**Comment by loyejaotdiqr47123** [comment]
> 这个是系统自身策略问题，可以先net stop termservice /y 停止服务后执行update.bat

这个方式好像也不行，目前解决方法未知

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/102934154/70bbd0c4-1691-40c1-819a-eab7897d1212)
添加了错误日志输出，的确是权限问题

**Comment by Mapaler** [comment]
> ![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/102934154/70bbd0c4-1691-40c1-819a-eab7897d1212)
> 添加了错误日志输出，的确是权限问题

这看起来不是权限，而是占用问题吧

**Comment by loyejaotdiqr47123** [comment]
好像确实，报错好像没看完整..

**Comment by loyejaotdiqr47123** [comment]
我这边上taskkill+net stop看看

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/102934154/da9396a8-614e-449d-a46f-38c50b216952)

**Comment by loyejaotdiqr47123** [comment]
通过`sc config termservice start=disabled`禁用`termservice`服务
然后结束进程正常更新

**Comment by loyejaotdiqr47123** [comment]
[RDPWrap-v1.8.4.1.zip](https://github.com/user-attachments/files/15847839/RDPWrap-v1.8.4.1.zip)

**Comment by loyejaotdiqr47123** [comment]
[v1.8.4.1](https://github.com/loyejaotdiqr47123/rdpwrap/releases/tag/v1.8.4.1)
