### ISSUE TITLE
win10更新后重装失败

### ISSUE THREAD

**Issue by TerryHoCQ** [loyejaotdiqr47123/rdpwrap#19]
![error](https://github.com/loyejaotdiqr47123/rdpwrap/assets/72144546/c6e532fe-2a00-4b88-9a22-4a351e5be4ea)
win10更新后无法更新，重装好几个版本都失败了，麻烦看下，谢谢

**Comment by TerryHoCQ** [comment]
执行install.bat后C:\Program Files\RDP Wrapper目录只有RDPWInst.exe文件

**Comment by loyejaotdiqr47123** [comment]
[RDPConf.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15111200/RDPConf.zip)

**Comment by loyejaotdiqr47123** [comment]
> ![error](https://private-user-images.githubusercontent.com/72144546/325449219-c6e532fe-2a00-4b88-9a22-4a351e5be4ea.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTQwNTgsIm5iZiI6MTcxNDA1Mzc1OCwicGF0aCI6Ii83MjE0NDU0Ni8zMjU0NDkyMTktYzZlNTMyZmUtMmEwMC00Yjg4LTlhMjItNGEzNTFlNWJlNGVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDE0MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNmVhZjc4YTQyMmQwNTFiNzIyOWZiMjMxNmE1OGUzZjY3NjRjY2EyMDI0NDQxMWE3YzkzOTg1ZGEzMDY4MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.htaM-jY706ZIontVAk-iczbPQc2555PAtPXwEN1N8ds) win10更新后无法更新，重装好几个版本都失败了，麻烦看下，谢谢

你不安装rdpwrap连接下rdp看看能不能连上（注意我指的是能不能连上，只是看下你rdp有不有更新炸了

**Comment by TerryHoCQ** [comment]
![error](https://github.com/loyejaotdiqr47123/rdpwrap/assets/72144546/4d7395f3-2c29-46c0-aa3e-bf5f523e5b17)

**Comment by loyejaotdiqr47123** [comment]
上传下termsrv.dll

**Comment by TerryHoCQ** [comment]
[termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15129870/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
[rdp.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15187366/rdp.zip)
覆盖注册表，然后就可以安装了

**Comment by TerryHoCQ** [comment]
> @TerryHoCQ [rdp.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15187366/rdp.zip) 覆盖注册表，然后就可以安装了

谢谢， 但是还是同样的错误提示

**Comment by loyejaotdiqr47123** [comment]
@TerryHoCQ qq加群，690838766

**Comment by loyejaotdiqr47123** [comment]
不加就算了，那我也不解决了，这本来就是你系统的问题

**Comment by TerryHoCQ** [comment]
> 不加就算了，那我也不解决了，这本来就是你系统的问题

非常抱歉，刚才出去了，麻烦再加一下，感谢感谢

**Comment by loyejaotdiqr47123** [comment]
> > 不加就算了，那我也不解决了，这本来就是你系统的问题
> 
> 非常抱歉，刚才出去了，麻烦再加一下，感谢感谢

qq加群690838766，然后顺便附上你截图
