### ISSUE TITLE
Windows 10 Release Preview b19041.4235

### ISSUE THREAD

**Issue by qaz1qazlol2** [loyejaotdiqr47123/rdpwrap#2]
https://github.com/stascorp/rdpwrap/issues/2524#issue-2199078394

离谱，微软重新发一个更新rdpwrap就炸了

**Comment by loyejaotdiqr47123** [comment]
[Add support : 19041.4235](https://github.com/loyejaotdiqr47123/rdpwrap/commit/db1f0a2e3e0f4ccbbeef009f0952ec3a81617872)
