### ISSUE TITLE
Windows11专业版 启用失败 本地多用户还是连不上

### ISSUE THREAD

**Issue by SoYeonQwQ** [loyejaotdiqr47123/rdpwrap#20]
[termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15261870/termsrv.zip)
<img width="305" alt="378ea7abe5de92fdff5c0f1a9c1e36bd" src="https://github.com/loyejaotdiqr47123/rdpwrap/assets/30514102/e73adf0e-cde7-4fa0-bc55-1fd7051ac294">
<img width="435" alt="60292dd7ac92347d91370ae56f6a175f" src="https://github.com/loyejaotdiqr47123/rdpwrap/assets/30514102/e65ba44d-598c-496f-b79e-cd360f19e757">
<img width="728" alt="f0de5c8481546814299a3b575ae6b21d" src="https://github.com/loyejaotdiqr47123/rdpwrap/assets/30514102/a40abfa0-c231-40b5-83c5-384dc48bf720">

**Comment by loyejaotdiqr47123** [comment]
> [termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15261870/termsrv.zip) <img alt="378ea7abe5de92fdff5c0f1a9c1e36bd" width="305" src="https://private-user-images.githubusercontent.com/30514102/329235921-e73adf0e-cde7-4fa0-bc55-1fd7051ac294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjYzNzMsIm5iZiI6MTcxNTQyNjA3MywicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5MjEtZTczYWRmMGUtY2RlNy00ZmEwLWJjNTUtMWZkNzA1MWFjMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjM2MxYzY1NzZhN2Y2ZDZhYzQ5YWFiNzkzYzgzODM0MTE4NjM4MjI4NTAxZWFiOTA4NmI3NGEwMDhmMzk0NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UokzhdZHB9L6dxZyrVUX07FZV5JLA6YsX9EOFU3fCw"> <img alt="60292dd7ac92347d91370ae56f6a175f" width="435" src="https://private-user-images.githubusercontent.com/30514102/329235931-e65ba44d-598c-496f-b79e-cd360f19e757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjYzNzMsIm5iZiI6MTcxNTQyNjA3MywicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5MzEtZTY1YmE0NGQtNTk4Yy00OTZmLWI3OWUtY2QzNjBmMTllNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZjExMWQ1YWE5NmNjYmRhYTM5ZGU0NmE5ZDkxODZhZWE5YjgzYTk3NTdiZDZiODhkYzMyMzVjZTk2YWUyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aymqi_Kp6fGiRku3bGEfp4i-JwGEQ_ha5tnZ5dRsByk"> <img alt="f0de5c8481546814299a3b575ae6b21d" width="728" src="https://private-user-images.githubusercontent.com/30514102/329235941-a40abfa0-c231-40b5-83c5-384dc48bf720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjYzNzMsIm5iZiI6MTcxNTQyNjA3MywicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5NDEtYTQwYWJmYTAtYzIzMS00MGI1LTgzYzUtMzg0ZGM0OGJmNzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYTA3YzQ1MWRkZDQ2NTI5ODQ0N2UzMWQ4OWM5MjdiYzVjNWY1NjQ1MmI4ZmMxNzgyZmMwNjdmNDUwNjYxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yeyqaqux8Wj3wcDccHuSRLn1MiX7XKluwQFbNwFwVNU">

qq加群690838766

**Comment by loyejaotdiqr47123** [comment]
> [termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/15261870/termsrv.zip) <img alt="378ea7abe5de92fdff5c0f1a9c1e36bd" width="305" src="https://private-user-images.githubusercontent.com/30514102/329235921-e73adf0e-cde7-4fa0-bc55-1fd7051ac294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0ODYwMjYsIm5iZiI6MTcxNTQ4NTcyNiwicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5MjEtZTczYWRmMGUtY2RlNy00ZmEwLWJjNTUtMWZkNzA1MWFjMjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAzNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMDZmZWE5OTVkYmQ5NjE0NWNmN2JhYzgyOTdjYzc1ZDgwNGNmNjIxMjkxYzg3MTVlZTNmMmQyZGU5MmVkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JSz_If4ILbESe-7J9ffs61-PMGUysLk6JuJvxNRITKA"> <img alt="60292dd7ac92347d91370ae56f6a175f" width="435" src="https://private-user-images.githubusercontent.com/30514102/329235931-e65ba44d-598c-496f-b79e-cd360f19e757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0ODYwMjYsIm5iZiI6MTcxNTQ4NTcyNiwicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5MzEtZTY1YmE0NGQtNTk4Yy00OTZmLWI3OWUtY2QzNjBmMTllNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAzNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwM2FmZWMzMzczZjRmOTRiM2Y3YmZhZjk2NGE3MmFkNWE2OWRiYjU1NGNiYzAzNGMxNTI4MDEyNDhhNmYyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9TwyQKgtLEcrnA4ywAbGTl80Uk6hhs-PYGyn2ZMHhk"> <img alt="f0de5c8481546814299a3b575ae6b21d" width="728" src="https://private-user-images.githubusercontent.com/30514102/329235941-a40abfa0-c231-40b5-83c5-384dc48bf720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0ODYwMjYsIm5iZiI6MTcxNTQ4NTcyNiwicGF0aCI6Ii8zMDUxNDEwMi8zMjkyMzU5NDEtYTQwYWJmYTAtYzIzMS00MGI1LTgzYzUtMzg0ZGM0OGJmNzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDAzNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMGUwNzBmNDA1MDE4NTZhNjRlOWVhN2I4YjE4YmYyOTE0YWUyZTQ5YjA1NjNhNjlhMjYxZWNmNDA4MTE3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lr8epIgMTRpi1sIZiYANMAO2hJHlLkdpy3LcLkwe-w4">

重启电脑后再看..你这个难搞，先上传下termsrv.dll

**Comment by SoYeonQwQ** [comment]
termsrv.dll我传了。
我现在是通过key把专业版切换为多用户企业版，就可以多用户远程桌面了

**Comment by loyejaotdiqr47123** [comment]
那应该不是rdpwrap的问题
