### ISSUE TITLE
请问SingleUserCode.x64的新值？

### ISSUE THREAD

**Issue by adream100** [loyejaotdiqr47123/rdpwrap#21]
我看到最近的更新中，这两个版本：
[10.0.19041.4355] 、 [10.0.19041.4474]
更换了SingleUserCode.x64值。
新值: SingleUserCode.x64=mov_eax_1_nop_2
旧值:   SingleUserCode.x64=Zero

这个更新是由同一个用户每次登录都会创建新会话引发的。

问题1：这个现象能重现么？我测试了4355与4474两个Win10版本，不能重现。另外，在我的测试环境中，新老两个值都工作正常。
问题2：是否意味着，所有版本都需要将旧值改为新值？
问题3：不改会怎样？

**Comment by loyejaotdiqr47123** [comment]
能重现，这个应该是修改了组策略的情况下，在rdp cnc中同一个用户多会话是用注册表控制的，旧值会导致注册表项无效，并且这实际上是winlogin的一个bug

这个影响所有版本，所以也意味着需要旧值全部改为新值

不改反正也没啥大毛病，至少能用

**Comment by loyejaotdiqr47123** [comment]
你可以看下[https://github.com/llccd/RDPWrapOffsetFinder/issues/10](https://github.com/llccd/RDPWrapOffsetFinder/issues/10)

**Comment by loyejaotdiqr47123** [comment]
在对新版本的更新中，我将使用新值

**Comment by adream100** [comment]
> 能重现，这个应该是修改了组策略的情况下，在rdp cnc中同一个用户多会话是用注册表控制的，旧值会导致注册表项无效，并且这实际上是winlogin的一个bug
> 
> 这个影响所有版本，所以也意味着需要旧值全部改为新值
> 
> 不改反正也没啥大毛病，至少能用

非常感谢您的回复。我想确切了解的是：修改组策略中的哪一项，可以重现该现象？因为我多次尝试，并没有找到：旧值可重现问题，然后改为新值后问题就能消失

**Comment by adream100** [comment]
我希望这个新值能获得实际验证。

**Comment by loyejaotdiqr47123** [comment]
你可以尝试在rdp cnc中关闭singleuser

**Comment by adream100** [comment]
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/153361306/35a3b47c-27bd-423e-ad3a-de2f54817e5f)
这个问题没有描述清楚，是我之前写得太简略了。那么现在我详细说一下。我的测试环境：Server是Win10 22H2当前最新（termsrv.dll版本：10.0.19041.4474），程序用的是您的版本：v1.8.4.1。

一、首先在Server中安装您的程序最新版本：v1.8.4.1，安装后rdpwrap.ini中[10.0.19041.4474]是新值：
SingleUserOffset.x64=1846B
SingleUserCode.x64=mov_eax_1_nop_2
1.如果取消Single session per user选项（不打勾），那么同一用户每次登录Server，Server都会为该用户产生一个新会话。
2.如果选择Single session per user选项（打勾），那么同一用户每次登录Server，Server都会为该用户维持唯一会话。
这个本来就是微软的设计。没有问题。从Win7到Win11，一直如此。
二、将rdpwrap.ini中[10.0.19041.4474]改为旧值：

SingleUserOffset.x64=1843B
SingleUserCode.x64=Zero
重启。重复刚才的测试，结果完全相同。旧值并不会导致这个选项失效。
也就是说，新旧值在这个选项的表现完全一致。那么修改的由来在哪？

**Comment by loyejaotdiqr47123** [comment]
> ![image](https://private-user-images.githubusercontent.com/153361306/340325466-35a3b47c-27bd-423e-ad3a-de2f54817e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTU2MTQsIm5iZiI6MTcxODcxNTMxNCwicGF0aCI6Ii8xNTMzNjEzMDYvMzQwMzI1NDY2LTM1YTNiNDdjLTI3YmQtNDIzZS1hZDNhLWRlMmY1NDgxN2U1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMjU1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTNmZjg3NGFjNzRiY2U1YWRjMTRhYjI3MWFlMDc5Yjg5MDY3ZjkwMDIwODZiOTI0YTY4ZmU2OTZjMzlmYzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGw3KIs53Wf-xhKrpvufaPvwH-jEd9OhBZkVVFX5X-0) 这个问题没有描述清楚，是我之前写得太简略了。那么现在我详细说一下。我的测试环境：Server是Win10 22H2当前最新（termsrv.dll版本：10.0.19041.4474），程序用的是您的版本：v1.8.4.1。
> 
> 一、首先在Server中安装您的程序最新版本：v1.8.4.1，安装后rdpwrap.ini中[10.0.19041.4474]是新值： SingleUserOffset.x64=1846B SingleUserCode.x64=mov_eax_1_nop_2 1.如果取消Single session per user选项（不打勾），那么同一用户每次登录Server，Server都会为该用户产生一个新会话。 2.如果选择Single session per user选项（打勾），那么同一用户每次登录Server，Server都会为该用户维持唯一会话。 这个本来就是微软的设计。没有问题。从Win7到Win11，一直如此。 二、将rdpwrap.ini中[10.0.19041.4474]改为旧值：
> 
> SingleUserOffset.x64=1843B SingleUserCode.x64=Zero 重启。重复刚才的测试，结果完全相同。旧值并不会导致这个选项失效。 也就是说，新旧值在这个选项的表现完全一致。那么修改的由来在哪？

这里使用不同版本来做示范
![image](https://github.com/loyejaotdiqr47123/rdpwrap/assets/102934154/f0d39028-3c8b-4c14-9d00-4465933122a3)
实际上，最终比对的是eax的值，旧值的位置是替换rsi的值。所以可能出现失效，使用新值是最好的

**Comment by loyejaotdiqr47123** [comment]
> ![image](https://private-user-images.githubusercontent.com/153361306/340325466-35a3b47c-27bd-423e-ad3a-de2f54817e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTU2MTQsIm5iZiI6MTcxODcxNTMxNCwicGF0aCI6Ii8xNTMzNjEzMDYvMzQwMzI1NDY2LTM1YTNiNDdjLTI3YmQtNDIzZS1hZDNhLWRlMmY1NDgxN2U1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMjU1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTNmZjg3NGFjNzRiY2U1YWRjMTRhYjI3MWFlMDc5Yjg5MDY3ZjkwMDIwODZiOTI0YTY4ZmU2OTZjMzlmYzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGw3KIs53Wf-xhKrpvufaPvwH-jEd9OhBZkVVFX5X-0) 这个问题没有描述清楚，是我之前写得太简略了。那么现在我详细说一下。我的测试环境：Server是Win10 22H2当前最新（termsrv.dll版本：10.0.19041.4474），程序用的是您的版本：v1.8.4.1。
> 
> 一、首先在Server中安装您的程序最新版本：v1.8.4.1，安装后rdpwrap.ini中[10.0.19041.4474]是新值： SingleUserOffset.x64=1846B SingleUserCode.x64=mov_eax_1_nop_2 1.如果取消Single session per user选项（不打勾），那么同一用户每次登录Server，Server都会为该用户产生一个新会话。 2.如果选择Single session per user选项（打勾），那么同一用户每次登录Server，Server都会为该用户维持唯一会话。 这个本来就是微软的设计。没有问题。从Win7到Win11，一直如此。 二、将rdpwrap.ini中[10.0.19041.4474]改为旧值：
> 
> SingleUserOffset.x64=1843B SingleUserCode.x64=Zero 重启。重复刚才的测试，结果完全相同。旧值并不会导致这个选项失效。 也就是说，新旧值在这个选项的表现完全一致。那么修改的由来在哪？

qq加群 聊吧
群号:690838766

**Comment by loyejaotdiqr47123** [comment]
有点解释不清楚了

**Comment by adream100** [comment]
是否可以理解为，旧值出现故障是小概率，需要在某些特定情形下发生，不太容易简单重现？OK，我们群里慢慢聊。
