### ISSUE TITLE
遇到一个新的问题，导致物理会话切换到新用户桌面

### ISSUE THREAD

**Issue by kz1989** [loyejaotdiqr47123/rdpwrap#22]
目前在几台windows server系统下出现，使用rdpwrap后，物理会话使用用户A，通过其他机器使用用户B登录后，物理会话 会切换到用户B的桌面，看了下任务管理器 当前用户是B.
![image](https://github.com/user-attachments/assets/5b173809-6dd1-413b-8ad2-5c9eb025c92a)

**Comment by loyejaotdiqr47123** [comment]
物理会话是指显示器的，还是指某些远控软件，例如向日葵，todesk

**Comment by kz1989** [comment]
服务器都在远程，用todesk连接观察到的，发现桌面会话切换到用户B了， 断开todesk应该是一样的，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月13日(周二) 上午10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [loyejaotdiqr47123/rdpwrap] 遇到一个新的问题，导致物理会话切换到新用户桌面 (Issue #22)




 
物理会话是指显示器的，还是指某些远控软件，例如向日葵，todesk

**Comment by kz1989** [comment]
> 物理会话是指显示器的，还是指某些远控软件，例如向日葵，todesk

刚才又验证了一下，首先用vnc连接到服务器登录用户A，然后又用todesk连接到服务器（看到的画面是用户A桌面），这个时候 mstsc登录用户B，这个时候todesk的桌面 是用户B了，vnc的桌面还是A，这是todesk搞的吗

**Comment by loyejaotdiqr47123** [comment]
todesk有一定概率会直接捕捉到运行todesk用户上的画面，而不是物理显示器
