### ISSUE TITLE
not support

### ISSUE THREAD

**Issue by broeeee** [loyejaotdiqr47123/rdpwrap#28]
10.0.20348.2760 不支持
![not support](https://github.com/user-attachments/assets/5c58e737-3311-4325-87aa-88ee68abab86)

**Comment by loyejaotdiqr47123** [comment]
[https://github.com/sebaxakerhtc/rdpwrap.ini/commit/a7ba302a06d09f20f27b3d8c62aee56caef02b14](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/a7ba302a06d09f20f27b3d8c62aee56caef02b14)
已经更新，可点update ini进行更新
