### ISSUE TITLE
Windows 11 termserv 10.0.22621.3374 not supported

### ISSUE THREAD

**Issue by Sharkta2** [loyejaotdiqr47123/rdpwrap#4]
Please help to update rdpwrap.ini Windows 11 termserv 10.0.22621.3374 not supported
[termsrv.zip](https://github.com/loyejaotdiqr47123/rdpwrap/files/14770770/termsrv.zip)

**Comment by Sharkta2** [comment]
[10.0.22621.3374]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3374-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C

**Comment by loyejaotdiqr47123** [comment]
Thx u

**Comment by loyejaotdiqr47123** [comment]
[https://github.com/loyejaotdiqr47123/rdpwrap/commit/88c1f8c997480d6473cb14eac351a7bb3bf520f2](https://github.com/loyejaotdiqr47123/rdpwrap/commit/88c1f8c997480d6473cb14eac351a7bb3bf520f2)
